[workspace]
resolver = "3"
members = ["backend","frontend", "import-linter","midend", "ooo_iter", "sbc", "trace"]

#[package]
#name = "substratum-compiler"
#version = "0.1.0"
#edition = "2021"

[workspace.features]
default = ["arch_RV64G"]
arch_RV64G = []

loud_lexing = []
loud_parsing = []


[workspace.dependencies]
trace = { path = "./trace" }
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"


[workspace.lints.rust]
unreachable_pub = "deny"
# TODO: remove
dead_code = "allow"

[workspace.lints.clippy]
pedantic = "warn"
use_self = "warn"
redundant_clone = "warn"
equatable_if_let = "warn"
needless_pass_by_ref_mut = "warn"
# TODO: enable me
# fallible_impl_from = "warn"
redundant_pub_crate = { level = "allow", priority = 1 }
# TODO: remove
unused_self = { level = "allow", priority = 1 }
