name: Clippy check

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings


      - name: lint imports 
        run: cargo run --bin import-linter frontend midend backend import-linter
        
        
      
  
